global:
  scrape_interval:     15s
  evaluation_interval: 15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'htd-bizapps-monitor'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "alert.rules"

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: 'htd-bizapps-monitor'
    scheme: https
    metrics_path: /metrics
    tls_config:
      cert_file: /etc/prometheus/certs/ssl_certificate.crt
      key_file:  /etc/prometheus/certs/ssl_certificate_key.key
    scrape_interval: 5s
    static_configs:
      - targets: ['htd-bizapps-monitor.cisco.com']

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'pushgateway'
    scrape_interval: 10s
    honor_labels: true
    static_configs:
      - targets: ['pushgateway:9091']


alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets: 
      - 'alertmanager:9093'

